### PR TITLE
Build with meson

### PR DESCRIPTION
**Pull request by spanezz**

### CODE REVIEW

**Comment by edigiacomo** [comment]
I have tried to modify the spec file to build the package with Meson but I don't know how to translate the configure command ` %configure --with-system-pdwt` to Meson.

I have tried with a simple

```
%meson
%meson_build
```

But I think that it tries to compile the bundled version of PublicDecompWT:

```
...
2024-10-28 14:19:38 INFO system.fedora40 stdout: Has header "stdint.h" : YES
2024-10-28 14:19:38 INFO system.fedora40 stdout: Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
2024-10-28 14:19:38 INFO system.fedora40 stdout: Run-time dependency magick++ found: YES 7.1.1
2024-10-28 14:19:38 INFO system.fedora40 stdout: Run-time dependency NetCDF for cpp found: YES 4.9.2
2024-10-28 14:19:38 INFO system.fedora40 stdout: Check usable header "netcdfcpp.h" : YES
2024-10-28 14:19:38 INFO system.fedora40 stdout: Library netcdf_c++ found: YES
2024-10-28 14:19:38 INFO system.fedora40 stdout: Program gdal-config found: YES (/usr/bin/gdal-config)
2024-10-28 14:19:38 INFO system.fedora40 stdout: WARNING: You should add the boolean check kwarg to the run_command call.
2024-10-28 14:19:38 INFO system.fedora40 stdout:          It currently defaults to false,
2024-10-28 14:19:38 INFO system.fedora40 stdout:          but it will default to true in future releases of meson.
2024-10-28 14:19:38 INFO system.fedora40 stdout:          See also: https://github.com/mesonbuild/meson/issues/9300
2024-10-28 14:19:38 INFO system.fedora40 stdout: Run-time dependency eccodes found: YES 2.38.0
2024-10-28 14:19:38 INFO system.fedora40 stdout: 
2024-10-28 14:19:38 INFO system.fedora40 stdout: decompress/meson.build:24:16: ERROR: Include dir PublicDecompWT/DISE/ does not exist.
...
```

**Comment by spanezz** [comment]
> I have tried to modify the spec file to build the package with Meson but I don't know how to translate the configure command ` %configure --with-system-pdwt` to Meson.

Oops, you're right, I forgot to port that one!

**Comment by spanezz** [comment]
> > I have tried to modify the spec file to build the package with Meson but I don't know how to translate the configure command ` %configure --with-system-pdwt` to Meson.
> 
> Oops, you're right, I forgot to port that one!

I pushed support for `-D system_pdwt=true` as a meson option.

Currently:

* if you do not specify it, the bundled one is used
* if you specify it and none is installed, the bunled one is used

Alternatively the default could be something else, like:

* use the system one and fallback to the bundled one if not found
* same but remove the meson option
* or if  `-D system_pdwt=true`  is set and none is installed, error out

**Comment by edigiacomo** [comment]
> * or if  `-D system_pdwt=true`  is set and none is installed, error out

This is the only requirement that we need to build the rpm, thanks!

**Comment by spanezz** [comment]
> > * or if  `-D system_pdwt=true`  is set and none is installed, error out
> This is the only requirement that we need to build the rpm, thanks!

Pushed!

**Comment by edigiacomo** [comment]
Now I have this error:

```
msat/meson.build:8:0: ERROR: File config.h does not exist.
```

See https://simc.arpae.it/moncic-ci/meteosatlib/202411061156/meson/rocky8/build.log

**Pull request merged**
